title: The Black List
email: ricoledan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A curated list about all kinds of Black People topics and resources for all people interested in the black experience.
baseurl: ''
url: 'https://ricoledan.github.io/the-black-list'
theme: jekyll-theme-minima
